KuetAcademy.Web/Controllers/AdminBlogPostController.cs
using KuetAcademy.Web.Models.Domain;
using KuetAcademy.Web.Models.ViewModels;
using KuetAcademy.Web.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace KuetAcademy.Web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBlogPostController : Controller
    {
        private readonly ITagRepository tagRepository;
        private readonly IBlogPostRepository blogPostRepository;

        public AdminBlogPostController(ITagRepository tagRepository, IBlogPostRepository blogPostRepository)
        {
            this.tagRepository = tagRepository;
            this.blogPostRepository = blogPostRepository;
        }
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            //get tags from repository
            var tags = await tagRepository.GetAllAsync();

            var model = new AddBlogPostRequest
            {
                Tags = tags.Select(x => new SelectListItem { Text = x.Name, Value = x.Id.ToString() })
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddBlogPostRequest addBlogPostRequest)
        {
            
            //map view model to domain model
            var blogpost = new BlogPost
            {
                Heading = addBlogPostRequest.Heading,
                Title = addBlogPostRequest.Title,
                Content = addBlogPostRequest.Content,
                ShortDescription = addBlogPostRequest.ShortDescription,
                FeaturedImageUrl = addBlogPostRequest.FeaturedImageUrl,
                UrlHandle = addBlogPostRequest.UrlHandle,
                PublishedDate = addBlogPostRequest.PublishedDate,
                Author = addBlogPostRequest.Author,
                Visible = addBlogPostRequest.Visible,
            };
            //map tags from selected tags
            var selectedTags = new List<Tag>();
            foreach (var selectedTagId in addBlogPostRequest.selectedTags)
            {
                var selectedTagIdAsGuid = Guid.Parse(selectedTagId);
                var existingTag = await tagRepository.GetAsync(selectedTagIdAsGuid);

                if (existingTag != null)
                {
                    selectedTags.Add(existingTag);
                }
            }
            //mapping tags back to domain model
            blogpost.Tags = selectedTags;
            
            await blogPostRepository.AddAsync(blogpost);
            TempData["addblog"] = " added a new blog";
            return RedirectToAction("List");
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            //call the repository
            var blogPosts = await blogPostRepository.GetAllAsync();

            return View(blogPosts);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            //retrieve the result from repo
            var blogPosts = await blogPostRepository.GetAsync(id);
            var tagsDomainModel = await tagRepository.GetAllAsync();
            //map the domain model into the view model
            if (blogPosts != null)
            {
                var model = new EditBlogPostRequest
                {
                    Id = blogPosts.Id,
                    Title = blogPosts.Title,
                    PublishedDate = blogPosts.PublishedDate,
                    Content = blogPosts.Content,
                    Author = blogPosts.Author,
                    Heading = blogPosts.Heading,
                    FeaturedImageUrl = blogPosts.FeaturedImageUrl,
                    UrlHandle = blogPosts.UrlHandle,
                    ShortDescription = blogPosts.ShortDescription,
                    Visible = blogPosts.Visible,
                    Tags = tagsDomainModel.Select(x => new SelectListItem
                    {
                        Text = x.Name,
                        Value = x.Id.ToString()
                    }),
                    selectedTags = blogPosts.Tags.Select(x => x.Id.ToString()).ToArray()
                };
                
                return View(model);
            }
            // pass data to view
            return View(null);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditBlogPostRequest editBlogPostRequest)
        {
            //map view model back to domain model

            var blogPostDomainModel = new BlogPost
            {
                Id = editBlogPostRequest.Id,
                Heading = editBlogPostRequest.Heading,
                Title = editBlogPostRequest.Title,
                Content = editBlogPostRequest.Content,
                Author = editBlogPostRequest.Author,
                ShortDescription = editBlogPostRequest.ShortDescription,
                FeaturedImageUrl = editBlogPostRequest.FeaturedImageUrl,
                UrlHandle = editBlogPostRequest.UrlHandle,
                PublishedDate = editBlogPostRequest.PublishedDate,
                Visible = editBlogPostRequest.Visible,
            };
            // map tags into domain model
            var selectedTags = new List<Tag>();
            foreach(var selectedTag in editBlogPostRequest.selectedTags) {
                if(Guid.TryParse(selectedTag, out var tag))
                {
                    var foundTag = await tagRepository.GetAsync(tag);

                    if (foundTag!=null)
                    {
                         selectedTags.Add(foundTag);                       
                    }
                }
            }
            
            blogPostDomainModel.Tags = selectedTags;

            //submit information to repository update
            var updatedBlog = await blogPostRepository.UpdateAsync(blogPostDomainModel);

            if(updatedBlog != null)
            {
                //show success notification
                TempData["update"] = " updated the blog";
                return RedirectToAction("Edit");
            }
            //show error
            TempData["notupdate"] = " something went wrong";
            return RedirectToAction("Edit");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(EditBlogPostRequest editBlogPostRequest)
        {
            //talk to repo to delete blogpost and tags
            var deletedBlog =  await blogPostRepository.DeleteAsync(editBlogPostRequest.Id);
            if(deletedBlog != null)
            {
                // show success notification
                TempData["delete"] = " deleted the blog";
                return RedirectToAction("List");
            }

            //show error
            TempData["notdelete"] = " something went wrong";
            return RedirectToAction("Edit", new { id = editBlogPostRequest.Id });
        }

    }
}

KuetAcademy.Web/Views/AdminBlogPost/Add.cshtml
@model KuetAcademy.Web.Models.ViewModels.AddBlogPostRequest
@{
}

<div style="background-color:#98EECC; opacity:inherit; border-radius:8px;">
    <div class="container">
        <h1>Add New Blog Post</h1>

    </div>
</div>

@if (TempData["addblog"] != null)
{
    <div class="alert alert-success">
        <strong>Succes</strong>@TempData["addblog"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
}
<div style="border-radius:10px; background-color:#F7FFE5">
    <div class="container py-2" style="font-size:18px; background-color:#F7FFE5">
        <br />
        <form method="post">

            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Page Title</label>
                <input type="text" class="form-control" id="pagetitle" asp-for="Title" />
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Short Description</label>
                <input type="text" class="form-control" id="shortdescription" asp-for="ShortDescription" />
               
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Featured Image Upload</label>
                <input type="file" id="featuredImageUpload" class="form-control" />

                <img src="" id="featuredImageDisplay" style="display:none; width:300px; height:300px; margin-top:5px;" />
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredimageurl" asp-for="FeaturedImageUrl" />
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Url Handle</label>
                <input type="text" class="form-control" id="urlhandle" asp-for="UrlHandle" />
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Published Date</label>
                <input type="date" class="form-control" id="publisheddate" asp-for="PublishedDate" />
                
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Author</label>
                <input type="text" class="form-control" id="author" asp-for="Author" />
                
            </div>
            <br />
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible" />
               
                <label style="font-weight:bold; font-size:20px; margin-left:5px;">
                    Is Visible?
                </label>
            </div>
            <br />
            <div class="mb-3">
                <label style="font-weight:bold; font-size:20px">Tags</label><br />
                <select class="form-group-lg" asp-items="@Model.Tags"
                        asp-for="selectedTags">
                </select>
            </div>
            <br />
            <div class="mb-3">
                <button type="submit" class="btn btn-primary" style="margin-right:5px; font-size:20px;">Save</button>
            </div>
            <br />
        </form>
    </div>
</div>

@section Scripts{
    <script>
        var editor = new FroalaEditor('#content',{
            imageUploadURL: '/api/images'
        });

        const featuredUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrlElement = document.getElementById('featuredimageurl');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e){
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file',e.target.files[0]);

            await fetch('/api/images',{
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageDisplayElement.src = result.link;
                    featuredImageDisplayElement.style.display = 'block';
                    featuredImageUrlElement.value = result.link;
                });
        } 

        featuredUploadElement.addEventListener('change',uploadFeaturedImage);

    </script>
}

KuetAcademy.Web/Views/AdminBlogPost/Edit.cshtml
@model KuetAcademy.Web.Models.ViewModels.EditBlogPostRequest
@{
}

<div style="background-color:#98EECC; opacity:inherit; border-radius:8px;">
    <div class="container">
        <h1>Edit Blog Post</h1>

    </div>
</div>
<br />

@if (TempData["update"] != null)
{
    <div class="alert alert-success">
        <strong>Succes</strong>@TempData["update"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
    <br />
}

@if (TempData["notupdate"] != null)
{
    <div class="alert alert-danger">
        <strong>Oops</strong>@TempData["notupdate"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
    <br>
}
@if (TempData["notdelete"] != null)
{
    <div class="alert alert-danger">
        <strong>Oops</strong>@TempData["notdelete"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
    <br>
}
<div class="container py-5" style="font-size:18px;">
    @if (Model != null)
    {
        <form method="post">
            <div class="mb-3">
                <label class="form-label">Id</label>
                <input type="text" class="form-control" id="id" asp-for="Id" readonly />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Heading</label>
                <input type="text" class="form-control" id="heading" asp-for="Heading" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Page Title</label>
                <input type="text" class="form-control" id="pagetitle" asp-for="Title" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Content</label>
                <textarea class="form-control" id="content" asp-for="Content"></textarea>
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Short Description</label>
                <input type="text" class="form-control" id="shortdescription" asp-for="ShortDescription" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Featured Image Upload</label>
                <input type="file" id="featuredImageUpload" class="form-control" />

                @if (Model.FeaturedImageUrl != null)
                {
                    <img src="@Model.FeaturedImageUrl" id="featuredImageDisplay" style="display:block; width:300px; height:300px; margin-top:5px;" />
                }
                else
                {
                    <img src="@Model.FeaturedImageUrl" id="featuredImageDisplay" style="display:none; width:300px; height:300px; margin-top:5px;" />

                }

            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Featured Image Url</label>
                <input type="text" class="form-control" id="featuredimageurl" asp-for="FeaturedImageUrl" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Url Handle</label>
                <input type="text" class="form-control" id="urlhandle" asp-for="UrlHandle" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Published Date</label>
                <input type="date" class="form-control" id="publisheddate" asp-for="PublishedDate" />
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Author</label>
                <input type="text" class="form-control" id="author" asp-for="Author" />
            </div>
            <br>
            <div class="form-check mb-3">
                <input class="form-check-input" type="checkbox" id="visible" asp-for="Visible">
                <label class="form-check-label">
                    Is Visible?
                </label>
            </div>
            <br>
            <div class="mb-3">
                <label class="form-label">Tags</label>
                <select class="form-select" asp-items="@Model.Tags"
                        asp-for="selectedTags">
                </select>
            </div>
            <br>
            <div class="mb-3 d-flex">
                <button type="submit" class="btn btn-primary" style="margin-right:5px;">Update</button>
                <button type="submit" class="btn btn-danger ms-3"
                        asp-area=""
                        asp-controller="AdminBlogPost"
                        asp-action="Delete">
                    Delete
                </button>
            </div>
        </form>
        <br />
    }
    else
    {
        <p>No blog post found</p>
    }

</div>

@section Scripts{
    <script>
        var editor = new FroalaEditor('#content', {
            imageUploadURL: '/api/images'
        });

        const featuredUploadElement = document.getElementById('featuredImageUpload');
        const featuredImageUrlElement = document.getElementById('featuredimageurl');
        const featuredImageDisplayElement = document.getElementById('featuredImageDisplay');


        async function uploadFeaturedImage(e) {
            console.log(e.target.files[0]);

            let data = new FormData();
            data.append('file', e.target.files[0]);

            await fetch('/api/images', {
                method: 'POST',
                headers: {
                    'Accept': '*/*',
                },
                body: data
            }).then(response => response.json())
                .then(result => {
                    featuredImageDisplayElement.src = result.link;
                    featuredImageDisplayElement.style.display = 'block';
                    featuredImageUrlElement.value = result.link;
                });
        }

        featuredUploadElement.addEventListener('change', uploadFeaturedImage);

    </script>
}

KuetAcademy.Web/Views/AdminBlogPost/List.cshtml
@model List<KuetAcademy.Web.Models.Domain.BlogPost>
@{
}

<div style="background-color:lightgrey; opacity:inherit; border-radius:8px;">
    <div class="container">
        <h1>All Blog Posts</h1>

    </div>
</div>
<br />

@if (TempData["delete"] != null)
{
    <div class="alert alert-success">
        <strong>Success</strong>@TempData["delete"]
        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
    </div>
    <br>
}
<div class="container" style="background-color:#FFF4F4;">
    @if(Model!= null && Model.Any())
    {
        <table class="table" style="font-size:16px;">
            <thead style="background-color:lightblue;">
                <tr style="font-size:20px;">
                    <th>ID</th>
                    <th>Heading</th>
                    <th>Tags</th>
                    <td> </td>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogpost in Model)
                {
                    <tr>
                        <td>@blogpost.Id</td>
                        <td>@blogpost.Heading</td>
                        <td>
                            <div class="d-flex">
                                @foreach (var item in blogpost.Tags)
                                {
                                    <span class="badge bg-secondary me-2">@item.Name</span>
                                }
                            </div>
                        </td>
                        <td>
                            <a asp-area=""
                               asp-controller="AdminBlogPost"
                               asp-action="Edit"
                               asp-route-id="@blogpost.Id">
                                <b>Edit</b>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No Blog Posts found</p>
    }

</div>
<br />
<br />